// Generated by CoffeeScript 1.4.0

$(document).ready(function() {
  return chrome.history.search({
    text: '',
    maxResults: 10000
  }, function(results) {
    var stats;
    return stats = _.chain(results).countBy(function(result) {
      return URI(result.url).domain();
    }).map(function(val, k) {
      return {
        domain: k,
        hits: val
      };
    }).each(function(o) {
      return $('body').append("" + o.domain + ": " + o.hits + "<br>");
    });
  });
});
